name: CI/CD

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.7'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Check formatting
        run: dart format --output=none .
        continue-on-error: true
      - name: Format files
        run: dart format .
      - name: Analyze project source
        run: flutter analyze
      - name: Run tests
        run: flutter test --coverage
      # - name: Upload coverage reports to Codecov
      #   uses: codecov/codecov-action@v3
      #   if: success()
      #   with:
      #     file: coverage/lcov.info
      #     fail_ci_if_error: true

  build-android:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.android/build-cache
            ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-android-${{ hashFiles('**/pubspec.lock', '**/build.gradle.kts', '**/settings.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-android-
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.7'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/app/keystore.jks
      - name: Create key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=keystore.jks" >> android/key.properties
      - name: Build APK
        run: flutter build apk --release
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-release-${{ github.run_number }}
          path: build/app/outputs/flutter-apk/app-release.apk
          retention-days: 90
          compression-level: 6
          overwrite: true

  build-web:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-web-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-web-
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.7'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build Web
        run: flutter build web --release
      - name: Upload Web Build
        uses: actions/upload-artifact@v4
        with:
          name: web-release-${{ github.run_number }}
          path: build/web
          retention-days: 90
          compression-level: 6
          overwrite: true

  build-windows:
    needs: test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/AppData/Local/Pub/Cache
            ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-windows-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-windows-
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.7'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build Windows
        run: flutter build windows --release
      - name: Upload Windows Build
        uses: actions/upload-artifact@v4
        with:
          name: windows-release-${{ github.run_number }}
          path: build/windows/x64/runner/Release/
          retention-days: 90
          compression-level: 6
          overwrite: true

  build-ios:
    needs: test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ~/Library/Caches/CocoaPods
            ${{ env.FLUTTER_HOME }}/.pub-cache
          key: ${{ runner.os }}-ios-${{ hashFiles('**/pubspec.lock', '**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-ios-
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.7'
          cache: true
      - name: Install dependencies
        run: flutter pub get
      - name: Build iOS
        run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          cp -r Runner.app Payload
          zip -r app.ipa Payload
      - name: Upload iOS Build
        uses: actions/upload-artifact@v4
        with:
          name: ios-release-${{ github.run_number }}
          path: build/ios/iphoneos/app.ipa
          retention-days: 90
          compression-level: 6
          overwrite: true